import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

interface EmbeddedAsset {
  contentType: string;
  body: string;
}

function toPosixPath(input: string): string {
  return input.split(path.sep).join("/");
}

function contentType(filePath: string): string {
  if (filePath.endsWith(".html")) return "text/html; charset=utf-8";
  if (filePath.endsWith(".js")) return "application/javascript; charset=utf-8";
  if (filePath.endsWith(".css")) return "text/css; charset=utf-8";
  if (filePath.endsWith(".svg")) return "image/svg+xml";
  if (filePath.endsWith(".json")) return "application/json; charset=utf-8";
  if (filePath.endsWith(".png")) return "image/png";
  if (filePath.endsWith(".jpg") || filePath.endsWith(".jpeg")) return "image/jpeg";
  if (filePath.endsWith(".webp")) return "image/webp";
  return "application/octet-stream";
}

function walk(dirPath: string): string[] {
  const out: string[] = [];
  const entries = readdirSync(dirPath, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      out.push(...walk(fullPath));
      continue;
    }

    if (entry.isFile()) {
      out.push(fullPath);
    }
  }

  return out;
}

function generateModule(assets: Record<string, EmbeddedAsset>): string {
  const serialized = JSON.stringify(assets, null, 2);

  return `// Generated by src/scripts/embed-ui-assets.ts\n// Do not edit manually.\n\nexport interface EmbeddedAsset {\n  contentType: string;\n  body: string;\n}\n\nexport const embeddedAssets: Record<string, EmbeddedAsset> = ${serialized};\n`;
}

function main(): void {
  const checkOnly = process.argv.includes("--check");
  const projectRoot = path.resolve(import.meta.dir, "../..");
  const distPath = path.join(projectRoot, "ui", "dist");
  const outPath = path.join(projectRoot, "src", "ui-server", "embedded-assets.ts");

  if (!existsSync(distPath) || !statSync(distPath).isDirectory()) {
    throw new Error(`UI dist folder not found at ${distPath}. Run "bun run build:ui" first.`);
  }

  const files = walk(distPath).sort((a, b) => a.localeCompare(b));
  const assets: Record<string, EmbeddedAsset> = {};

  for (const absolutePath of files) {
    const relativePath = toPosixPath(path.relative(distPath, absolutePath));
    const routePath = `/${relativePath}`;
    assets[routePath] = {
      contentType: contentType(relativePath),
      body: readFileSync(absolutePath).toString("base64"),
    };
  }

  const nextModule = generateModule(assets);

  if (checkOnly) {
    const existingModule = existsSync(outPath) ? readFileSync(outPath, "utf8") : "";
    if (existingModule !== nextModule) {
      throw new Error(
        `Embedded UI assets are stale at ${outPath}. Run "bun run embed:ui" to regenerate.`,
      );
    }

    console.log(`Embedded UI assets are up to date (${Object.keys(assets).length} file(s)).`);
    return;
  }

  writeFileSync(outPath, nextModule, "utf8");
  console.log(`Embedded ${Object.keys(assets).length} UI asset(s) into ${outPath}`);
}

main();
